# Permalinks
permalink:           pretty

# Setup
title:               Dan Roth Data Science
tagline:             Dan Roth's Personal Brew of Data Science
url:                 http://danrothdatascience.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Dan Roth
  url:               http://danrothdatascience.github.io
  email:             rdan689@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/DanRothDataScience

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
